//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Braille_Shape_Generator_Client.ShapeGeneratorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShapeGeneratorService.Shape_Generator_ServiceSoap")]
    public interface Shape_Generator_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circle", ReplyAction="*")]
        double Circle(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CircleAsync(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Triangle", ReplyAction="*")]
        double Triangle(double height, double width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Triangle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> TriangleAsync(double height, double width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rectangle", ReplyAction="*")]
        double Rectangle(double width, double height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rectangle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RectangleAsync(double width, double height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Square", ReplyAction="*")]
        double Square(double length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Square", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SquareAsync(double length);
        
        // CODEGEN: Generating message contract since element name number from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBrailleDots", ReplyAction="*")]
        Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponse GetBrailleDots(Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBrailleDots", ReplyAction="*")]
        System.Threading.Tasks.Task<Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponse> GetBrailleDotsAsync(Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBrailleDotsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBrailleDots", Namespace="http://tempuri.org/", Order=0)]
        public Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequestBody Body;
        
        public GetBrailleDotsRequest() {
        }
        
        public GetBrailleDotsRequest(Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBrailleDotsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        public GetBrailleDotsRequestBody() {
        }
        
        public GetBrailleDotsRequestBody(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBrailleDotsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBrailleDotsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponseBody Body;
        
        public GetBrailleDotsResponse() {
        }
        
        public GetBrailleDotsResponse(Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBrailleDotsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetBrailleDotsResult;
        
        public GetBrailleDotsResponseBody() {
        }
        
        public GetBrailleDotsResponseBody(int GetBrailleDotsResult) {
            this.GetBrailleDotsResult = GetBrailleDotsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Shape_Generator_ServiceSoapChannel : Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Shape_Generator_ServiceSoapClient : System.ServiceModel.ClientBase<Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap>, Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap {
        
        public Shape_Generator_ServiceSoapClient() {
        }
        
        public Shape_Generator_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Shape_Generator_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Shape_Generator_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Shape_Generator_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Circle(double radius) {
            return base.Channel.Circle(radius);
        }
        
        public System.Threading.Tasks.Task<double> CircleAsync(double radius) {
            return base.Channel.CircleAsync(radius);
        }
        
        public double Triangle(double height, double width) {
            return base.Channel.Triangle(height, width);
        }
        
        public System.Threading.Tasks.Task<double> TriangleAsync(double height, double width) {
            return base.Channel.TriangleAsync(height, width);
        }
        
        public double Rectangle(double width, double height) {
            return base.Channel.Rectangle(width, height);
        }
        
        public System.Threading.Tasks.Task<double> RectangleAsync(double width, double height) {
            return base.Channel.RectangleAsync(width, height);
        }
        
        public double Square(double length) {
            return base.Channel.Square(length);
        }
        
        public System.Threading.Tasks.Task<double> SquareAsync(double length) {
            return base.Channel.SquareAsync(length);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponse Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap.GetBrailleDots(Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest request) {
            return base.Channel.GetBrailleDots(request);
        }
        
        public int GetBrailleDots(string number) {
            Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest inValue = new Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest();
            inValue.Body = new Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequestBody();
            inValue.Body.number = number;
            Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponse retVal = ((Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap)(this)).GetBrailleDots(inValue);
            return retVal.Body.GetBrailleDotsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponse> Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap.GetBrailleDotsAsync(Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest request) {
            return base.Channel.GetBrailleDotsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsResponse> GetBrailleDotsAsync(string number) {
            Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest inValue = new Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequest();
            inValue.Body = new Braille_Shape_Generator_Client.ShapeGeneratorService.GetBrailleDotsRequestBody();
            inValue.Body.number = number;
            return ((Braille_Shape_Generator_Client.ShapeGeneratorService.Shape_Generator_ServiceSoap)(this)).GetBrailleDotsAsync(inValue);
        }
    }
}
